"""
Django settings for gestionlocationbackend project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured
import dj_database_url


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Charger les variables d'environnement depuis le fichier .env
load_dotenv(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-local-development-only-change-me'
    else:
        raise ImproperlyConfigured('SECRET_KEY doit etre defini quand DEBUG=False.')

_allowed = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1')
ALLOWED_HOSTS = [host.strip() for host in _allowed.split(',') if host.strip()]
for host in ('carloc.onrender.com', os.environ.get('RENDER_EXTERNAL_HOSTNAME', '')):
    if host and host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(host)


def env_bool(name: str, default: bool = False) -> bool:
    return os.environ.get(name, str(default)).lower() in ('1', 'true', 'yes', 'on')


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'cloudinary_storage',
    'cloudinary',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'gestionlocationbackend',
    'corsheaders',
    'rest_framework_simplejwt',
    'drf_spectacular',
    'api.apps.ApiConfig',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'api.monitoring.middleware.PrometheusMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'api.middleware.AuditContextMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '100/min',
    },
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'EXCEPTION_HANDLER': 'api.exception_handler.carloc_exception_handler',
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}

# ============================================================================
# CELERY — tâches asynchrones (emails, sync parc)
# ============================================================================

CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', CELERY_BROKER_URL)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_MAX_RETRIES = 3
CELERY_TASK_DEFAULT_RETRY_DELAY = 60
CELERY_TASK_ALWAYS_EAGER = env_bool('CELERY_TASK_ALWAYS_EAGER', DEBUG)
CELERY_TASK_EAGER_PROPAGATES = True

# ============================================================================
# CACHE — Redis (dashboard) ou mémoire locale (tests)
# ============================================================================

_redis_url = os.environ.get('REDIS_URL', '').strip()
if _redis_url:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': _redis_url,
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'carloc-cache',
        }
    }

DASHBOARD_CACHE_ENABLED = env_bool('DASHBOARD_CACHE_ENABLED', True)
DASHBOARD_CACHE_TTL = int(os.environ.get('DASHBOARD_CACHE_TTL', '300'))

# ============================================================================
# STOCKAGE FICHIERS — chiffrement + S3 optionnel
# ============================================================================

CARLOC_FILE_ENCRYPTION_KEY = os.environ.get('CARLOC_FILE_ENCRYPTION_KEY', '')
AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME', '').strip()
AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'eu-west-3')
AWS_S3_CUSTOM_DOMAIN = os.environ.get('AWS_S3_CUSTOM_DOMAIN', '')
AWS_DEFAULT_ACL = 'private'
AWS_QUERYSTRING_AUTH = True

if AWS_STORAGE_BUCKET_NAME:
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID', '')
    AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY', '')

CELERY_BEAT_SCHEDULE = {
    'sync-vehicle-status-every-hour': {
        'task': 'api.tasks.sync_all_vehicle_status',
        'schedule': 3600.0,
    },
}

# OpenAPI / Swagger — documentation interactive CarLoc
SPECTACULAR_SETTINGS = {
    'TITLE': 'CarLoc API',
    'DESCRIPTION': (
        'API REST de gestion d\'agence de location de véhicules : '
        'parc, clients, réservations, contrats, paiements, factures et tableau de bord.'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': r'/api',
    'TAGS': [
        {'name': 'auth', 'description': 'Authentification JWT'},
        {'name': 'vehicules', 'description': 'Gestion du parc automobile'},
        {'name': 'clients', 'description': 'Gestion des clients'},
        {'name': 'reservations', 'description': 'Réservations et disponibilité'},
        {'name': 'contrats', 'description': 'Contrats de location'},
        {'name': 'paiements', 'description': 'Paiements et acomptes'},
        {'name': 'factures', 'description': 'Factures PDF'},
        {'name': 'maintenances', 'description': 'Maintenance du parc'},
        {'name': 'reporting', 'description': 'Tableau de bord et statistiques'},
        {'name': 'notifications', 'description': 'Journal des e-mails envoyés'},
    ],
}
# CORS - Origines autorisees pour Angular/API.
_cors_default = 'http://localhost:4200,http://127.0.0.1:4200'
_cors = os.environ.get('CORS_ALLOWED_ORIGINS', _cors_default)
CORS_ALLOWED_ORIGINS = [origin.strip() for origin in _cors.split(',') if origin.strip()]
for origin in (
    'https://carloc-smoky.vercel.app',
    'https://carloc-git-main-rostandngabas-projects.vercel.app',
):
    if origin not in CORS_ALLOWED_ORIGINS:
        CORS_ALLOWED_ORIGINS.append(origin)
CORS_ALLOWED_ORIGIN_REGEXES = [
    r'^https://carloc(-.*)?-rostandngabas-projects\.vercel\.app$',
]

_csrf = os.environ.get('CSRF_TRUSTED_ORIGINS', '')
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in _csrf.split(',') if origin.strip()]
for origin in (
    'https://carloc-smoky.vercel.app',
    'https://carloc-git-main-rostandngabas-projects.vercel.app',
):
    if origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(origin)

# Durcissement HTTP. Activez SECURE_SSL_REDIRECT/HSTS uniquement derriere HTTPS.
SECURE_SSL_REDIRECT = env_bool('SECURE_SSL_REDIRECT', False)
SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', False)
SECURE_HSTS_PRELOAD = env_bool('SECURE_HSTS_PRELOAD', False)
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = os.environ.get('SECURE_REFERRER_POLICY', 'same-origin')
X_FRAME_OPTIONS = 'DENY'
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = env_bool('SESSION_COOKIE_SECURE', False)
CSRF_COOKIE_SECURE = env_bool('CSRF_COOKIE_SECURE', False)
# JWT — Durée de vie des tokens
from datetime import timedelta
SIMPLE_JWT = {
 'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
 'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}
# Autoriser les méthodes HTTP
CORS_ALLOW_METHODS = [
 'GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'
]
# Autoriser les en-têtes personnalisés (dont Authorization JWT)
CORS_ALLOW_HEADERS = [
 'accept', 'accept-encoding', 'authorization',
 'content-type', 'dnt', 'origin', 'user-agent',
 'x-csrftoken', 'x-requested-with',
]

ROOT_URLCONF = 'gestionlocationbackend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gestionlocationbackend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'carloc_db'),
        'USER': os.environ.get('DB_USER', 'postgres'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'root'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}

# --- AJOUTE CE BLOC JUSTE EN DESSOUS ---
# Si le projet tourne sur Render, on écrase la config avec la variable DATABASE_URL
if os.environ.get('DATABASE_URL'):
    DATABASES['default'] = dj_database_url.config(conn_max_age=600, ssl_require=True)


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators
# En DEBUG, pas de validateurs : pratique pour mots de passe courts en local (ex. admin « 123 »).
# En production (DEBUG=False), règles Django complètes.

if DEBUG:
    AUTH_PASSWORD_VALIDATORS: list[dict[str, str]] = []
else:
    AUTH_PASSWORD_VALIDATORS = [
        {
            'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
        },
    ]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Africa/Douala'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (Images des véhicules, documents clients)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# E-mail — notifications CarLoc
# Développement sans SMTP : EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend',
)
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'localhost')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'False') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
# Avec Gmail, l'expéditeur doit en général être identique à EMAIL_HOST_USER
DEFAULT_FROM_EMAIL = os.environ.get(
    'DEFAULT_FROM_EMAIL',
    EMAIL_HOST_USER or 'noreply@carloc.cm',
)
CARLOC_ADMIN_EMAIL = os.environ.get('CARLOC_ADMIN_EMAIL', EMAIL_HOST_USER or 'admin@carloc.cm')
EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', '30'))

# --- Interface Django Admin (Jazzmin) — thème CarLoc ---
JAZZMIN_SETTINGS = {
    'site_title': 'CarLoc Admin',
    'site_header': 'CarLoc',
    'site_brand': 'CarLoc · Administration',
    'site_logo': None,
    'login_logo': None,
    'welcome_sign': 'Bienvenue dans l’administration CarLoc',
    'copyright': 'CarLoc — Gestion de location',
    'search_model': ['auth.User', 'api.Client', 'api.Vehicule', 'api.Reservation'],
    'user_avatar': None,
    'topmenu_links': [
        {'name': 'Accueil', 'url': 'admin:index', 'permissions': ['auth.view_user']},
        {'name': 'API Swagger', 'url': '/api/docs/', 'new_window': True},
        {'name': 'Site Angular', 'url': 'https://carloc-smoky.vercel.app/admin', 'new_window': True},
    ],
    'usermenu_links': [
        {'model': 'auth.user'},
    ],
    'show_sidebar': True,
    'navigation_expanded': True,
    'hide_apps': [],
    'hide_models': [],
    'order_with_respect_to': [
        'api',
        'api.Vehicule',
        'api.Client',
        'api.Reservation',
        'api.Contrat',
        'api.Paiement',
        'api.Facture',
        'api.Maintenance',
        'api.NotificationLog',
        'auth',
    ],
    'icons': {
        'auth': 'fas fa-users-cog',
        'auth.user': 'fas fa-user-shield',
        'auth.group': 'fas fa-users',
        'api.Vehicule': 'fas fa-car',
        'api.Client': 'fas fa-address-card',
        'api.Reservation': 'fas fa-calendar-check',
        'api.Paiement': 'fas fa-money-bill-wave',
        'api.Contrat': 'fas fa-file-signature',
        'api.Facture': 'fas fa-file-invoice-dollar',
        'api.Maintenance': 'fas fa-wrench',
        'api.NotificationLog': 'fas fa-envelope',
    },
    'default_icon_parents': 'fas fa-folder',
    'default_icon_children': 'fas fa-circle',
    'related_modal_active': True,
    'custom_css': None,
    'custom_js': None,
    'use_google_fonts_cdn': True,
    'show_ui_builder': False,
    'changeform_format': 'horizontal_tabs',
    'changeform_format_overrides': {
        'auth.user': 'collapsible',
        'auth.group': 'vertical_tabs',
    },
}

JAZZMIN_UI_TWEAKS = {
    'navbar_small_text': False,
    'footer_small_text': False,
    'body_small_text': False,
    'brand_small_text': False,
    'brand_colour': 'navbar-danger',
    'accent': 'accent-danger',
    'navbar': 'navbar-dark navbar-danger',
    'no_navbar_border': False,
    'navbar_fixed': True,
    'layout_boxed': False,
    'footer_fixed': False,
    'sidebar_fixed': True,
    'sidebar': 'sidebar-dark-danger',
    'sidebar_nav_small_text': False,
    'sidebar_disable_expand': False,
    'sidebar_nav_child_indent': True,
    'sidebar_nav_compact_style': False,
    'sidebar_nav_legacy_style': False,
    'sidebar_nav_flat_style': True,
    'theme': 'flatly',
    'dark_mode_theme': None,
    'button_classes': {
        'primary': 'btn-danger',
        'secondary': 'btn-outline-secondary',
        'info': 'btn-info',
        'warning': 'btn-warning',
        'danger': 'btn-outline-danger',
        'success': 'btn-success',
    },
}

# ============================================================================
# LOGGING — Configuration du logging structuré en JSON
# ============================================================================

import os

# Créer le dossier logs s'il n'existe pas
LOGS_DIR = BASE_DIR / 'logs'
os.makedirs(LOGS_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'json': {
            '()': 'api.logging_config.CustomJsonFormatter',
        },
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'json',
            'level': 'INFO',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'carloc.log',
            'maxBytes': 10485760,  # 10MB
            'backupCount': 5,
            'formatter': 'json',
            'level': 'DEBUG',
        },
        'business_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'business.log',
            'maxBytes': 10485760,  # 10MB
            'backupCount': 5,
            'formatter': 'json',
            'level': 'INFO',
        },
        'audit_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'audit.log',
            'maxBytes': 10485760,  # 10MB
            'backupCount': 10,
            'formatter': 'json',
            'level': 'INFO',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'carloc': {
            'handlers': ['console', 'file', 'business_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'carloc.audit': {
            'handlers': ['audit_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'api': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
}

# ============================================================================
# MONITORING — Sentry (erreurs) + Prometheus (métriques)
# ============================================================================

SENTRY_DSN = os.environ.get('SENTRY_DSN', '').strip()
SENTRY_TRACES_SAMPLE_RATE = os.environ.get('SENTRY_TRACES_SAMPLE_RATE', '0.1')
SENTRY_ENVIRONMENT = os.environ.get(
    'SENTRY_ENVIRONMENT',
    'development' if DEBUG else 'production',
)

PROMETHEUS_ENABLED = env_bool('PROMETHEUS_ENABLED', DEBUG)
PROMETHEUS_METRICS_TOKEN = os.environ.get('PROMETHEUS_METRICS_TOKEN', '').strip()

from gestionlocationbackend.sentry_config import init_sentry  # noqa: E402

SENTRY_ENABLED = init_sentry(debug=DEBUG)
