# Generated by Django 6.0.3 on 2026-05-18 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_client_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paiement",
            name="reservation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paiements",
                to="api.reservation",
            ),
        ),
        migrations.CreateModel(
            name="Contrat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_signature", models.DateTimeField(auto_now_add=True)),
                (
                    "kilometrage_depart",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "kilometrage_retour",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "penalites_retard",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "fichier_pdf",
                    models.FileField(blank=True, null=True, upload_to="contrats/"),
                ),
                (
                    "reservation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contrat",
                        to="api.reservation",
                    ),
                ),
            ],
        ),
    ]
