# Generated by Django 6.0.5 on 2026-05-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_client_num_cni_client_photo_profil_client_solde_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationlog",
            name="type_notification",
            field=models.CharField(
                choices=[
                    ("reservation_creee", "Réservation créée"),
                    ("reservation_annulee", "Réservation annulée"),
                    ("paiement_recu", "Paiement reçu"),
                    ("facture_emise", "Facture emise"),
                ],
                max_length=30,
            ),
        ),
    ]
