# Generated by Django 6.0.5 on 2026-05-23 07:57

import api.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_notificationlog_type_notification"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="num_cni",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                validators=[api.validators.validate_cni_format],
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="num_permis",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                validators=[api.validators.validate_permis_format],
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="permis_conduire",
            field=models.FileField(
                blank=True,
                help_text="Scan du permis de conduire",
                null=True,
                upload_to="documents_clients/permis/",
                validators=[api.validators.validate_document_file],
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="piece_identite",
            field=models.FileField(
                blank=True,
                help_text="Scan de la pièce d'identité",
                null=True,
                upload_to="documents_clients/identite/",
                validators=[api.validators.validate_document_file],
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="telephone",
            field=models.CharField(
                max_length=20, validators=[api.validators.validate_telephone_format]
            ),
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(help_text="ID de l'objet modifié"),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Créé"),
                            ("update", "Modifié"),
                            ("delete", "Supprimé"),
                            ("cancel", "Annulé"),
                            ("finalize", "Finalisé"),
                        ],
                        help_text="Type de modification",
                        max_length=10,
                    ),
                ),
                (
                    "old_values",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="État de l'objet AVANT la modification",
                    ),
                ),
                (
                    "new_values",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="État de l'objet APRÈS la modification",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Moment de la modification",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="Adresse IP du client", null=True
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        help_text="Raison de la modification (optionnel)",
                        max_length=255,
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Utilisateur qui a effectué l'action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="Type d'objet modifié (Reservation, Contrat, etc.)",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log d'audit",
                "verbose_name_plural": "Logs d'audit",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="api_auditlo_content_3674ae_idx",
                    ),
                    models.Index(
                        fields=["-timestamp"], name="api_auditlo_timesta_96ac8f_idx"
                    ),
                    models.Index(
                        fields=["action"], name="api_auditlo_action_0a1743_idx"
                    ),
                    models.Index(
                        fields=["actor"], name="api_auditlo_actor_i_662f04_idx"
                    ),
                ],
            },
        ),
    ]
