# Generated by Django 6.0.5 on 2026-05-23 09:09

import django.db.models.deletion
from decimal import Decimal

from django.conf import settings
from django.db import migrations, models


def seed_default_configuration(apps, schema_editor):
    ConfigurationMetier = apps.get_model("api", "ConfigurationMetier")
    defaults = [
        (
            "PENALTY_MULTIPLICATEUR",
            "penalty",
            Decimal("1.5"),
            "Multiplicateur pénalité retard",
        ),
        ("REFUND_RATE_48H", "refund", Decimal("1.0"), "Remboursement >48h"),
        ("REFUND_RATE_24H", "refund", Decimal("0.8"), "Remboursement 24-48h"),
        ("REFUND_RATE_LATE", "refund", Decimal("0.5"), "Remboursement <24h"),
    ]
    for key, category, value, description in defaults:
        ConfigurationMetier.objects.get_or_create(
            key=key,
            defaults={
                "category": category,
                "value_decimal": value,
                "description": description,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_total_paye_cache_and_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="vehicule",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicule",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.CreateModel(
            name="ConfigurationMetier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Clé unique: PENALTY_MULTIPLICATEUR",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("penalty", "Pénalités"),
                            ("refund", "Remboursement"),
                            ("pricing", "Tarification"),
                            ("system", "Système"),
                        ],
                        default="system",
                        max_length=20,
                    ),
                ),
                ("value_str", models.TextField(blank=True)),
                ("value_int", models.IntegerField(blank=True, null=True)),
                (
                    "value_decimal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("value_bool", models.BooleanField(default=False)),
                ("description", models.TextField(help_text="Description pour l'admin")),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="config_modifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration métier",
                "verbose_name_plural": "Configurations métier",
                "ordering": ["category", "key"],
            },
        ),
        migrations.RunPython(seed_default_configuration, migrations.RunPython.noop),
    ]
