# Generated by Django 6.0.5 on 2026-05-29 14:50

import api.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_client_permis_conduire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, storage=api.storages.get_public_image_storage, upload_to='clients/photos/'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=api.storages.get_public_image_storage, upload_to='vehicules/'),
        ),
    ]
